### ISSUE TITLE
TestCoolKeeperTradeBasicSad fails

### ISSUE THREAD

**Issue by philipstanislaus** [thorchain/THORChain#20] opened 2018-09-03 18:06 UTC
**Describe the bug**
TestCoolKeeperTradeBasicSad fails on master

**To Reproduce**
1. Run `make test`

**Expected behavior**
Test succeeds

**Screenshots**
<img width="600" alt="bildschirmfoto 2018-09-03 um 20 04 34" src="https://user-images.githubusercontent.com/6912756/44998313-c6422d80-afb4-11e8-8eff-d996102165f7.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 10.13.6

**Comment by musnit** [comment] 2018-09-03 20:58
cannot reproduce

**Comment by philipstanislaus** [comment] 2018-09-07 09:19
Just tried again on master – I still get this error @musnit

**Comment by musnit** [comment] 2018-09-07 17:19
fixed by #26

**Closed by musnit** 2018-09-07 17:19 UTC
